### ISSUE TITLE
Placeholder suggestions (TPS, MSPT, Playername)

### ISSUE THREAD

**Issue by JelCraft** [Sytm/simple-player-list#3]
I've loved the plugin ever since I got it. Light and straight to the point!

I do have a few more suggestions for placeholders though. It would be really nice if we could display the server TPS, MSPT and have a placeholder for player names (so it could show "Welcome to the server, %playername%! | TPS: %TPS%", or something like that).

Thanks in advance!

**Comment by Sytm** [comment]
I'll look into it tomorrow
